#!/usr/bin/env node
/**
 * Loforger postinstall script.
 *
 * Detects the current OS/filesystem and creates the appropriate CLI wrapper
 * so `loforger` works on every platform without manual setup.
 *
 * Strategies:
 *   - Unix with native filesystem (ext4, apfs, zfs, …):
 *       npm's bin symlink already works — nothing to do.
 *   - Unix on NTFS/FUSE (WSL, external drives):
 *       npm's symlink may fail. We create a shell wrapper that calls
 *       node directly, bypassing the need for executable permissions.
 *   - Windows (cmd.exe / PowerShell):
 *       npm creates a .cmd shim automatically from the "bin" field.
 *       We write a fallback .cmd next to the package.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import crypto from "node:crypto";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.join(__dirname, "..");
const isWindows = process.platform === "win32";

/**
 * Check whether the filesystem supports Unix-style chmod.
 * Uses a unique temp file to avoid race conditions in parallel installs.
 */
function filesystemSupportsChmod(dir) {
	const testFile = path.join(
		dir,
		`.loforger-fs-test-${process.pid}-${crypto.randomBytes(4).toString("hex")}`,
	);
	try {
		fs.writeFileSync(testFile, "");
		fs.chmodSync(testFile, 0o755);
		fs.unlinkSync(testFile);
		return true;
	} catch {
		try {
			fs.unlinkSync(testFile);
		} catch {
			/* already gone */
		}
		return false;
	}
}

/**
 * Locate a writable bin directory for this package.
 * npm puts bins in `node_modules/.bin/` (local) or `<prefix>/bin/` (global).
 */
function findBinDir() {
	const possible = [
		path.join(pkgRoot, "..", "..", ".bin"), // local: node_modules/.bin
		path.join(pkgRoot, "..", "..", "..", "bin"), // global: <prefix>/bin
		path.join(pkgRoot, "..", "..", "bin"), // global alternative
	];

	for (const dir of possible) {
		const resolved = path.resolve(dir);
		if (fs.existsSync(resolved)) {
			try {
				fs.accessSync(resolved, fs.constants.W_OK);
				return resolved;
			} catch {
				continue;
			}
		}
	}

	return null;
}

/**
 * Create a Unix shell wrapper at `dest` that execs node with our entry point.
 * Uses an absolute path resolved at generation time so spaces in paths are safe.
 */
function writeShellWrapper(dest) {
	const entryAbs = path.normalize(path.join(pkgRoot, "dist", "index.js"));
	const content = `#!/bin/sh
# Loforger CLI wrapper — auto-generated by postinstall
exec node "${entryAbs}" "$@"
`;
	fs.writeFileSync(dest, content, { mode: 0o755 });
	try {
		fs.chmodSync(dest, 0o755);
	} catch (err) {
		const msg = err.message || "";
		if (!msg.includes("EPERM") && !msg.includes("EACCES") && !msg.includes("EOPNOTSUPP")) {
			console.warn(`loforger: Warning — failed to set permissions: ${msg}`);
		}
	}
}

/**
 * Create a Windows .cmd wrapper at `dest`.
 */
function writeCmdWrapper(dest) {
	const entryAbs = path.normalize(path.join(pkgRoot, "dist", "index.js")).replace(/\//g, "\\");
	const content = `@echo off\r\nnode "${entryAbs}" %*\r\n`;
	try {
		fs.writeFileSync(dest, content);
	} catch (err) {
		console.warn(`loforger: Warning — failed to write .cmd wrapper: ${err.message}`);
	}
}

// ── Main ──

if (isWindows) {
	// On Windows npm already creates a .cmd shim from the "bin" field.
	// Write a fallback .cmd next to the package for edge cases.
	const fallback = path.join(pkgRoot, "loforger.cmd");
	writeCmdWrapper(fallback);
	console.log("loforger: Windows environment detected — .cmd wrapper ready.");
} else {
	// Unix — check if filesystem supports executable permissions.
	const binDir = findBinDir();

	if (binDir && !filesystemSupportsChmod(binDir)) {
		// NTFS/FUSE detected — create wrapper that doesn't rely on chmod.
		const wrapperPath = path.join(binDir, "loforger");
		writeShellWrapper(wrapperPath);
		console.log("loforger: NTFS/FUSE filesystem detected — shell wrapper created.");
	} else if (!binDir) {
		// Could not find bin dir (e.g. running inside a monorepo or unusual layout).
		// Not an error — the user may be using npx or a different install method.
		console.log("loforger: Skipping wrapper creation (non-standard install layout).");
	}
	// If chmod works, npm's default symlink is sufficient — nothing to do.
}
